name: CI

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install

      - name: Run markdown lint
        run: |
          npm install
          npx remark . \
          --use remark-preset-wooorm \  # 修正拼写
          --use remark-preset-lint-consistent \
          --frail \  # 修正参数
          --no-stdout \
          --silent
      
